# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0002_auto_20170208_0033'),
        ('projectflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_member',
            field=models.ManyToManyField(to='teamflow.TeamMember'),
        ),
    ]
