# Generated by Django 5.2.2 on 2025-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this project will be visible to all users'),
        ),
    ]
