# Generated by Django 5.2.2 on 2025-06-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectflow', '0002_project_is_public'),
        ('teamflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='teamflow.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='projectflow.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teamflow.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to='teamflow.teammember'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teamflow.teammember'),
        ),
    ]
