# Generated by Django 5.2.2 on 2025-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectflow', '0003_project_assigned_teams_project_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('standard', 'Standard Project'), ('roadmap', 'Feature Roadmap')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the task'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, help_text='Designate this task as a milestone in the project timeline'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the project timeline'),
        ),
    ]
