# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=320, null=True),
        ),
    ]
