# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='donatemethod',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='donatemethod',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='usertree',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='usertree',
            name='updated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
