# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170103_0328'),
    ]

    operations = [
        # Temporarily removing the programs field to fix migration issues
    ]
