# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revprograms', '0001_initial'),
        ('accounts', '0005_auto_20170103_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='programs',
            field=models.ManyToManyField(related_name='programs_entered', to='revprograms.RevenupaPrograms'),
        ),
    ]
