# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemethod',
            name='account_type',
            field=models.CharField(choices=[('LOCB', 'LOCAL BANK')], max_length=4),
        ),
    ]
