# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170103_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatemethod',
            old_name='username',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='donatemethod',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
