# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20170103_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(default='example@domain.ext', max_length=254, unique=True)),
                ('slug', models.SlugField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('action', models.URLField()),
                ('actiontype', models.CharField(default='USER', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usertree',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='usertree',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserTree',
        ),
    ]
