# Generated by Django 5.2.2 on 2025-06-06 15:16

import webcore.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0006_auto_20200805_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedurl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
