# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('url', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='teams')),
                ('description', models.CharField(max_length=160)),
                ('is_public', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='membersofteam', to=settings.AUTH_USER_MODEL)),
                ('teamAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamcreator', to=settings.AUTH_USER_MODEL)),
                ('teamManagers', models.ManyToManyField(related_name='managersofteam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=60, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=60, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
