# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0002_auto_20170208_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(default='example@domain.ext', max_length=254, unique=True)),
                ('slug', models.SlugField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('action', models.URLField()),
                ('actiontype', models.CharField(default='USER', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailSignUp',
        ),
        migrations.AlterUniqueTogether(
            name='teaminvites',
            unique_together=set([('email', 'team')]),
        ),
    ]
