# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0003_auto_20170208_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvites',
            name='declined',
        ),
        migrations.AlterField(
            model_name='teaminvites',
            name='accepted',
            field=models.NullBooleanField(default=False),
        ),
    ]
