# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0005_teaminvites_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamInvites',
            new_name='TeamInvite',
        ),
    ]
