# Generated by Django 5.2.2 on 2025-06-09 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0008_auto_20200805_0858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamAuthor',
        ),
        migrations.RemoveField(
            model_name='team',
            name='url',
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
        migrations.AddField(
            model_name='team',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='token',
            field=models.CharField(default='default-token', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='teaminvite',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teaminvite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='handle',
        ),
    ]
