# Generated by Django 5.2.2 on 2025-06-09 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Administrator'), ('platform_user', 'Platform User'), ('workspace_admin', 'Workspace Administrator'), ('workspace_member', 'Workspace Member'), ('workspace_guest', 'Workspace Guest'), ('team_manager', 'Team Manager'), ('team_member', 'Team Member'), ('project_manager', 'Project Manager'), ('project_member', 'Project Member'), ('project_viewer', 'Project Viewer')], max_length=30)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='invites_inv_content_b45bda_idx'), models.Index(fields=['token'], name='invites_inv_token_e4bb9a_idx'), models.Index(fields=['email', 'accepted'], name='invites_inv_email_3b1530_idx')],
            },
        ),
    ]
